In [1]:
import numpy as np
from math import sqrt
from math import sin, cos, pi

In [2]:
def sphericalToCartesian(r,theta,phi):
    return [r*sin(phi/180*pi)*cos(theta/180*pi), r*sin(phi/180*pi)*sin(theta/180*pi),r*cos(phi/180*pi)]

In [23]:
r = np.array([1,0,0])
s = np.array([0,1,0])
p = np.array([1/sqrt(2),0,1/sqrt(2)])
q = np.array([0,1/sqrt(2),1/sqrt(2)])

In [7]:
P = np.array(sphericalToCartesian(1,0,50))
Q = np.array(sphericalToCartesian(1,90,70))
S = np.array(sphericalToCartesian(1,90,90))
R = np.array(sphericalToCartesian(1,0,90))

In [83]:
P = np.array(sphericalToCartesian(1,0,60))
Q = np.array(sphericalToCartesian(1,90,60))
S = np.array(sphericalToCartesian(1,90,90))
R = np.array(sphericalToCartesian(1,0,90))

In [84]:
R = np.array([1,0,0])
S = np.array([1/sqrt(2),1/sqrt(2),0])
P = np.array([1/sqrt(2),0,1/sqrt(2)])
Q = np.array([1/2,1/2,1/sqrt(2)])

In [85]:
B = np.random.rand(4,3)
B

array([[0.74670318, 0.83771226, 0.1760313 ],
       [0.79565805, 0.22059202, 0.47889838],
       [0.79706635, 0.39934723, 0.30080425],
       [0.29665987, 0.56625906, 0.27824528]])

In [86]:
b1 = B[0,:]
b2 = B[1,:]
b3 = B[2,:]
b4 = B[3,:]

In [87]:
b1 = np.array(sphericalToCartesian(1,30,60))
b2 = np.array(sphericalToCartesian(1,60,60))
b3 = np.array(sphericalToCartesian(1,60,90))
b4 = np.array(sphericalToCartesian(1,30,90))

In [88]:
b1 = b1 / np.linalg.norm(b1)
b2 = b2 / np.linalg.norm(b2)
b3 = b3 / np.linalg.norm(b3)
b4 = b4 / np.linalg.norm(b4)

In [89]:
def ExemplaryTransformationQuadrilateral(p,q,r,s,P,Q,R,S):
    sq = np.cross(s,q)
    ps = np.cross(p,s)
    qp = np.cross(q,p)
    rqp = np.array([r,q,p])
    drqp = np.linalg.det(rqp)
    rps = np.array([r,p,s])
    drps = np.linalg.det(rps)
    rsq = np.array([r,s,q])
    drsq = np.linalg.det(rsq)
    SRQ = np.array([S,R,Q])
    dSRQ = np.linalg.det(SRQ)
    PRS = np.array([P,R,S])
    dPRS = np.linalg.det(PRS)
    QRP = np.array([Q,R,P])
    dQRP = np.linalg.det(QRP)
    sqP = np.outer(sq,P)
    psQ = np.outer(ps,Q)
    qpS = np.outer(qp,S)
        
    T1 = drqp*drps*dSRQ*sqP
    T2 = drqp*drsq*dPRS*psQ
    T3 = drps*drsq*dQRP*qpS
    
    return T1 + T2 + T3


In [90]:
Tac = ExemplaryTransformationQuadrilateral(p,q,s,r,P,Q,S,R)

In [91]:
Tab = ExemplaryTransformationQuadrilateral(p,q,s,r,b1,b2,b3,b4)

In [92]:
Tbc = ExemplaryTransformationQuadrilateral(b1,b2,b3,b4,P,Q,S,R)

In [93]:
Tcb = ExemplaryTransformationQuadrilateral(P,Q,S,R,b1,b2,b3,b4)

In [94]:
u, sigma, vh = np.linalg.svd(Tac, full_matrices=True)

In [95]:
print(u)

[[-7.07106781e-01  1.57009246e-16  7.07106781e-01]
 [-7.07106781e-01 -4.44089210e-16 -7.07106781e-01]
 [-2.02996189e-16  1.00000000e+00 -4.25040794e-16]]


In [96]:
print(sigma)

[0.11548494 0.08838835 0.04783543]


In [97]:
print(vh)

[[-9.23879533e-01 -3.82683432e-01 -1.20169674e-16]
 [ 0.00000000e+00 -3.14018492e-16  1.00000000e+00]
 [ 3.82683432e-01 -9.23879533e-01 -2.90115257e-16]]


In [115]:
A = np.array([p,q,s,r])
print(A)

[[0.70710678 0.         0.70710678]
 [0.         0.70710678 0.70710678]
 [0.         1.         0.        ]
 [1.         0.         0.        ]]


In [106]:
A = np.array([P,Q,R,S])
print(A)

[[0.70710678 0.         0.70710678]
 [0.5        0.5        0.70710678]
 [1.         0.         0.        ]
 [0.70710678 0.70710678 0.        ]]


In [116]:
u, sigma, vh = np.linalg.svd(A, full_matrices=True)

In [117]:
u

array([[-0.57735027,  0.40824829,  0.40824829, -0.57735027],
       [-0.57735027, -0.40824829,  0.40824829,  0.57735027],
       [-0.40824829, -0.57735027, -0.57735027, -0.40824829],
       [-0.40824829,  0.57735027, -0.57735027,  0.40824829]])

In [118]:
sigma

array([1.41421356, 1.22474487, 0.70710678])

In [119]:
vh

array([[-5.77350269e-01, -5.77350269e-01, -5.77350269e-01],
       [ 7.07106781e-01, -7.07106781e-01,  3.33066907e-16],
       [-4.08248290e-01, -4.08248290e-01,  8.16496581e-01]])

In [120]:
ud = np.linalg.det(u)
ud

-0.9999999999999998

In [121]:
vhd = np.linalg.det(vh)
vhd

0.9999999999999998

In [123]:
1/(sigma[0]*sigma[1]*sigma[2])**2

0.6666666666666667

In [18]:
W,V = np.linalg.eig(Tac)

In [19]:
print(W)
print(V)

[0.15100569 0.06550066 0.05496158]
[[ 0.00000000e+00  1.00000000e+00 -3.80560594e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.86253434e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [16]:
np.linalg.norm(np.matmul(s,Tac))

0.10825317547305481

In [17]:
np.linalg.norm(np.matmul(p,Tac))

0.08838834764831842

In [18]:
np.linalg.norm(np.matmul(q,Tac))

0.08838834764831842

In [19]:
np.linalg.norm(np.matmul(r,Tac))

0.1082531754730548

In [20]:
S

array([6.123234e-17, 1.000000e+00, 6.123234e-17])

In [21]:
np.matmul(s,Tac)*S[np.argmax(S)]/np.matmul(s,Tac)[np.argmax(S)]

array([-1.28197512e-16,  1.00000000e+00,  6.12323400e-17])

In [22]:
np.matmul(s,Tac)/np.linalg.norm(np.matmul(s,Tac))

array([-1.28197512e-16,  1.00000000e+00,  6.12323400e-17])

In [23]:
P

array([0.8660254, 0.       , 0.5      ])

In [24]:
np.matmul(p,Tac)*P[np.argmax(P)]/np.matmul(p,Tac)[np.argmax(P)]

array([0.8660254, 0.       , 0.5      ])

In [25]:
np.matmul(p,Tac)/np.linalg.norm(np.matmul(p,Tac))

array([0.8660254, 0.       , 0.5      ])

In [26]:
Q

array([5.30287619e-17, 8.66025404e-01, 5.00000000e-01])

In [27]:
np.matmul(q,Tac)*Q[np.argmax(Q)]/np.matmul(q,Tac)[np.argmax(Q)]

array([0.       , 0.8660254, 0.5      ])

In [28]:
np.matmul(q,Tac)/np.linalg.norm(np.matmul(q,Tac))

array([0.       , 0.8660254, 0.5      ])

In [29]:
R

array([1.000000e+00, 0.000000e+00, 6.123234e-17])

In [30]:
np.matmul(r,Tac)*R[np.argmax(R)]/np.matmul(r,Tac)[np.argmax(R)]

array([1.000000e+00, 0.000000e+00, 6.123234e-17])

In [31]:
np.matmul(r,Tac)/np.linalg.norm(np.matmul(r,Tac))

array([1.000000e+00, 0.000000e+00, 6.123234e-17])

In [32]:
W,V = np.linalg.eig(Tab)

In [33]:
print(W)
print(V)

[0.06375852 0.00246945 0.0118258 ]
[[-0.03552714 -0.89837177 -0.05159685]
 [-0.36725332 -0.33048972 -0.96248648]
 [-0.92944221  0.28931766  0.26637857]]


In [61]:
np.linalg.norm(V[:,2])

1.0

In [66]:
np.matmul(p,Tab)/V[0]

array([-0.32360707, -0.01038563, -0.82720686])

In [34]:
np.linalg.norm(np.matmul(p,Tab))

0.045176542547571176

In [35]:
np.linalg.norm(np.matmul(q,Tab))

0.05900600664111821

In [36]:
np.linalg.norm(np.matmul(s,Tab))

0.025061646527490936

In [37]:
np.linalg.norm(np.matmul(r,Tab))

0.0034838493088038803

In [38]:
b1

array([0.25448683, 0.20652655, 0.94476623])

In [39]:
np.matmul(p,Tab)*b1[np.argmax(b1)]/np.matmul(p,Tab)[np.argmax(b1)]

array([0.25448683, 0.20652655, 0.94476623])

In [40]:
np.matmul(p,Tab)/np.linalg.norm(np.matmul(p,Tab))

array([0.25448683, 0.20652655, 0.94476623])

In [41]:
b2

array([0.17000682, 0.34848971, 0.92176602])

In [42]:
np.matmul(q,Tab)*b2[np.argmax(b2)]/np.matmul(q,Tab)[np.argmax(b2)]

array([0.17000682, 0.34848971, 0.92176602])

In [43]:
np.matmul(q,Tab)/np.linalg.norm(np.matmul(q,Tab))

array([0.17000682, 0.34848971, 0.92176602])

In [44]:
b3

array([0.02562755, 0.67465728, 0.7376861 ])

In [45]:
np.matmul(s,Tab)*b3[np.argmax(b3)]/np.matmul(s,Tab)[np.argmax(b3)]

array([0.02562755, 0.67465728, 0.7376861 ])

In [46]:
np.matmul(s,Tab)/np.linalg.norm(np.matmul(s,Tab))

array([0.02562755, 0.67465728, 0.7376861 ])

In [47]:
b4

array([0.77921671, 0.29346875, 0.55380268])

In [48]:
np.matmul(r,Tab)*b4[np.argmax(b4)]/np.matmul(r,Tab)[np.argmax(b4)]

array([0.77921671, 0.29346875, 0.55380268])

In [49]:
np.matmul(r,Tab)/np.linalg.norm(np.matmul(r,Tab))

array([0.77921671, 0.29346875, 0.55380268])

In [ ]:
P

In [ ]:
np.matmul(b1,Tbc)*P[np.argmax(P)]/np.matmul(b1,Tbc)[np.argmax(P)]

In [ ]:
Q

In [ ]:
np.matmul(b2,Tbc)*Q[np.argmax(Q)]/np.matmul(b2,Tbc)[np.argmax(Q)]

In [ ]:
S

In [ ]:
np.matmul(b3,Tbc)*S[np.argmax(S)]/np.matmul(b3,Tbc)[np.argmax(S)]

In [ ]:
R

In [ ]:
np.matmul(b4,Tbc)*R[np.argmax(R)]/np.matmul(b4,Tbc)[np.argmax(R)]

In [ ]:
sq = np.cross(s,q)
print(sq)

In [ ]:
np.outer(sq,P)

In [ ]:
ps = np.cross(p,s)
print(ps)

In [ ]:
qp = np.cross(q,p)
print(qp)

In [ ]:
rqp = np.array([r,q,p])
drqp = np.linalg.det(rqp)
print (rqp)
print(drqp)

In [ ]:
rps = np.array([r,p,s])
drps = np.linalg.det(rps)
print (rps)
print(drps)

In [ ]:
rsq = np.array([r,s,q])
drsq = np.linalg.det(rsq)
print (rsq)
print(drsq)

In [ ]:
SRQ = np.array([S,R,Q])
dSRQ = np.linalg.det(SRQ)
print (SRQ)
print(dSRQ)

In [ ]:
PRS = np.array([P,R,S])
dPRS = np.linalg.det(PRS)
print (PRS)
print(dPRS)

In [ ]:
QRP = np.array([Q,R,P])
dQRP = np.linalg.det(QRP)
print (QRP)
print(dQRP)

In [ ]:
sqP = np.outer(sq,P)
print(sqP)

In [ ]:
psQ = np.outer(ps,Q)
print(psQ)

In [ ]:
qpS = np.outer(qp,S)
print(qpS)

In [ ]:
T1 = drqp*drps*dSRQ*sqP
print(T1)

In [ ]:
T2 = drqp*drsq*dPRS*psQ
print(T2)

In [ ]:
T3 = drps*drsq*dQRP*qpS
print(T3)

In [ ]:
T = T1+T2+T3
print(T)

In [ ]:
dT = np.linalg.det(T)
print(dT)

In [ ]:
qT = np.matmul(q,T)
print(qT)

In [ ]:
Q

In [ ]:
beta = Q[0]/qT[0]
print(beta)

In [ ]:
pT = np.matmul(p,T)
print(pT)

In [ ]:
P

In [ ]:
alpha = P[0]/pT[0]
print(alpha)

In [ ]:
sT = np.matmul(s,T)
print(sT)

In [ ]:
S

In [ ]:
gamma = S[0]/sT[0]
print(gamma)

In [ ]:
rT = np.matmul(r,T)
print(rT)

In [ ]:
R

In [ ]:
delta = R[0]/rT[0]

In [ ]:
T = alpha*T

In [ ]:
dT2 = np.linalg.det(T)
print(dT2)

In [ ]:
dTac = np.linalg.det(Tac)
print(dTac)

In [ ]:
dT2*dT2*3/4

In [ ]:
3/8

In [ ]:
dTab = np.linalg.det(Tab)
print(dTab)

In [ ]:
dTbc = np.linalg.det(Tbc)
print(dTbc)

In [ ]:
dTab*dTbc

In [ ]:
(dTab*dTbc)**2*3/4

In [ ]:
Quadrance_B = dTab**2*3/4
Quadrance_B

In [ ]:
Quadrance_B*dTbc**2

In [ ]:
dTcb = np.linalg.det(Tcb)
print(dTcb)

In [ ]:
0.375*dTcb**2

In [ ]:
dTcb*dTbc

In [39]:
A1 = np.array([p,q,s])
print(A1)

[[0.70710678 0.         0.70710678]
 [0.         0.70710678 0.70710678]
 [0.         1.         0.        ]]


In [40]:
A2 = np.array([p,s,r])
print(A2)

[[0.70710678 0.         0.70710678]
 [0.         1.         0.        ]
 [1.         0.         0.        ]]


In [41]:
A3 = np.array([p,q,r])
print(A3)

[[0.70710678 0.         0.70710678]
 [0.         0.70710678 0.70710678]
 [1.         0.         0.        ]]


In [42]:
A4 = np.array([q,s,r])
print(A4)

[[0.         0.70710678 0.70710678]
 [0.         1.         0.        ]
 [1.         0.         0.        ]]


In [43]:
C1 = np.array([P,Q,S])
print(C1)

[[8.66025404e-01 0.00000000e+00 5.00000000e-01]
 [5.30287619e-17 8.66025404e-01 5.00000000e-01]
 [6.12323400e-17 1.00000000e+00 6.12323400e-17]]


In [44]:
C2 = np.array([P,S,R])
print(C2)

[[8.66025404e-01 0.00000000e+00 5.00000000e-01]
 [6.12323400e-17 1.00000000e+00 6.12323400e-17]
 [1.00000000e+00 0.00000000e+00 6.12323400e-17]]


In [45]:
C3 = np.array([P,Q,R])
print(C3)

[[8.66025404e-01 0.00000000e+00 5.00000000e-01]
 [5.30287619e-17 8.66025404e-01 5.00000000e-01]
 [1.00000000e+00 0.00000000e+00 6.12323400e-17]]


In [46]:
C4 = np.array([Q,S,R])
print(A4)

[[0.         0.70710678 0.70710678]
 [0.         1.         0.        ]
 [1.         0.         0.        ]]


In [47]:
B1 = np.array([b1,b2,b3])
print(B1)

[[7.50000000e-01 4.33012702e-01 5.00000000e-01]
 [4.33012702e-01 7.50000000e-01 5.00000000e-01]
 [5.00000000e-01 8.66025404e-01 6.12323400e-17]]


In [48]:
B2 = np.array([b1,b3,b4])
print(B2)

[[7.50000000e-01 4.33012702e-01 5.00000000e-01]
 [5.00000000e-01 8.66025404e-01 6.12323400e-17]
 [8.66025404e-01 5.00000000e-01 6.12323400e-17]]


In [49]:
B3 = np.array([b1,b2,b4])
print(B3)

[[7.50000000e-01 4.33012702e-01 5.00000000e-01]
 [4.33012702e-01 7.50000000e-01 5.00000000e-01]
 [8.66025404e-01 5.00000000e-01 6.12323400e-17]]


In [50]:
B4 = np.array([b2,b3,b4])
print(B4)

[[4.33012702e-01 7.50000000e-01 5.00000000e-01]
 [5.00000000e-01 8.66025404e-01 6.12323400e-17]
 [8.66025404e-01 5.00000000e-01 6.12323400e-17]]


In [51]:
A1t = A1.transpose()
print(A1t)

[[0.70710678 0.         0.        ]
 [0.         0.70710678 1.        ]
 [0.70710678 0.70710678 0.        ]]


In [52]:
A2t = A2.transpose()
print(A2t)

[[0.70710678 0.         1.        ]
 [0.         1.         0.        ]
 [0.70710678 0.         0.        ]]


In [53]:
A3t = A3.transpose()
print(A3t)

[[0.70710678 0.         1.        ]
 [0.         0.70710678 0.        ]
 [0.70710678 0.70710678 0.        ]]


In [54]:
A4t = A4.transpose()
print(A4t)

[[0.         0.         1.        ]
 [0.70710678 1.         0.        ]
 [0.70710678 0.         0.        ]]


In [55]:
B1t = B1.transpose()
print(B1t)

[[7.50000000e-01 4.33012702e-01 5.00000000e-01]
 [4.33012702e-01 7.50000000e-01 8.66025404e-01]
 [5.00000000e-01 5.00000000e-01 6.12323400e-17]]


In [56]:
B2t = B2.transpose()
print(B2t)

[[7.50000000e-01 5.00000000e-01 8.66025404e-01]
 [4.33012702e-01 8.66025404e-01 5.00000000e-01]
 [5.00000000e-01 6.12323400e-17 6.12323400e-17]]


In [57]:
B3t = B3.transpose()
print(B3t)

[[7.50000000e-01 4.33012702e-01 8.66025404e-01]
 [4.33012702e-01 7.50000000e-01 5.00000000e-01]
 [5.00000000e-01 5.00000000e-01 6.12323400e-17]]


In [58]:
B4t = B4.transpose()
print(B4t)

[[4.33012702e-01 5.00000000e-01 8.66025404e-01]
 [7.50000000e-01 8.66025404e-01 5.00000000e-01]
 [5.00000000e-01 6.12323400e-17 6.12323400e-17]]


In [59]:
C1t = C1.transpose()
print(C1t)

[[8.66025404e-01 5.30287619e-17 6.12323400e-17]
 [0.00000000e+00 8.66025404e-01 1.00000000e+00]
 [5.00000000e-01 5.00000000e-01 6.12323400e-17]]


In [60]:
C2t = C2.transpose()
print(C2t)

[[8.66025404e-01 6.12323400e-17 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [5.00000000e-01 6.12323400e-17 6.12323400e-17]]


In [61]:
C3t = C3.transpose()
print(C3t)

[[8.66025404e-01 5.30287619e-17 1.00000000e+00]
 [0.00000000e+00 8.66025404e-01 0.00000000e+00]
 [5.00000000e-01 5.00000000e-01 6.12323400e-17]]


In [62]:
C4t = C4.transpose()
print(C4t)

[[5.30287619e-17 6.12323400e-17 1.00000000e+00]
 [8.66025404e-01 1.00000000e+00 0.00000000e+00]
 [5.00000000e-01 6.12323400e-17 6.12323400e-17]]


In [63]:
U1 = np.matmul(A1,A1t)
U1

array([[1.        , 0.5       , 0.        ],
       [0.5       , 1.        , 0.70710678],
       [0.        , 0.70710678, 1.        ]])

In [64]:
U2 = np.matmul(A2,A2t)
U2

array([[1.        , 0.        , 0.70710678],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 1.        ]])

In [65]:
U3 = np.matmul(A3,A3t)
U3

array([[1.        , 0.5       , 0.70710678],
       [0.5       , 1.        , 0.        ],
       [0.70710678, 0.        , 1.        ]])

In [66]:
U4 = np.matmul(A4,A4t)
U4

array([[1.        , 0.70710678, 0.        ],
       [0.70710678, 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

In [67]:
V1 = np.matmul(B1,B1t)
V1

array([[1.        , 0.89951905, 0.75      ],
       [0.89951905, 1.        , 0.8660254 ],
       [0.75      , 0.8660254 , 1.        ]])

In [68]:
V2 = np.matmul(B2,B2t)
V2

array([[1.       , 0.75     , 0.8660254],
       [0.75     , 1.       , 0.8660254],
       [0.8660254, 0.8660254, 1.       ]])

In [69]:
V3 = np.matmul(B3,B3t)
V3

array([[1.        , 0.89951905, 0.8660254 ],
       [0.89951905, 1.        , 0.75      ],
       [0.8660254 , 0.75      , 1.        ]])

In [70]:
V4 = np.matmul(B4,B4t)
V4

array([[1.       , 0.8660254, 0.75     ],
       [0.8660254, 1.       , 0.8660254],
       [0.75     , 0.8660254, 1.       ]])

In [71]:
W1 = np.matmul(C1,C1t)
W1

array([[1.00000000e+00, 2.50000000e-01, 8.36449319e-17],
       [2.50000000e-01, 1.00000000e+00, 8.66025404e-01],
       [8.36449319e-17, 8.66025404e-01, 1.00000000e+00]])

In [72]:
W2 = np.matmul(C2,C2t)
W2

array([[1.00000000e+00, 8.36449319e-17, 8.66025404e-01],
       [8.36449319e-17, 1.00000000e+00, 6.12323400e-17],
       [8.66025404e-01, 6.12323400e-17, 1.00000000e+00]])

In [73]:
W3 = np.matmul(C3,C3t)
W3

array([[1.00000000e+00, 2.50000000e-01, 8.66025404e-01],
       [2.50000000e-01, 1.00000000e+00, 8.36449319e-17],
       [8.66025404e-01, 8.36449319e-17, 1.00000000e+00]])

In [74]:
W4 = np.matmul(C4,C4t)
W4

array([[1.00000000e+00, 8.66025404e-01, 8.36449319e-17],
       [8.66025404e-01, 1.00000000e+00, 6.12323400e-17],
       [8.36449319e-17, 6.12323400e-17, 1.00000000e+00]])

In [75]:
Quadrance_A1 = np.linalg.det(U1)/(U1[0,0]*U1[1,1]*U1[2,2])
Quadrance_A1

0.2499999999999999

In [76]:
Quadrance_A2 = np.linalg.det(U2)/(U2[0,0]*U2[1,1]*U2[2,2])
Quadrance_A2

0.5

In [77]:
Quadrance_A3 = np.linalg.det(U3)/(U3[0,0]*U3[1,1]*U3[2,2])
Quadrance_A3

0.2499999999999999

In [78]:
Quadrance_A4 = np.linalg.det(U4)/(U4[0,0]*U4[1,1]*U4[2,2])
Quadrance_A4

0.5

In [79]:
Quadrance_B1 = np.linalg.det(V1)/(V1[0,0]*V1[1,1]*V1[2,2])
Quadrance_B1

0.04687499999999999

In [ ]:
Quadrance_B2 = np.linalg.det(V2)/(V2[0,0]*V2[1,1]*V2[2,2])
Quadrance_B2

In [ ]:
Quadrance_B3 = np.linalg.det(V3)/(V3[0,0]*V3[1,1]*V3[2,2])
Quadrance_B3

In [ ]:
Quadrance_B4 = np.linalg.det(V4)/(V4[0,0]*V4[1,1]*V4[2,2])
Quadrance_B4

In [ ]:
dTab = np.linalg.det(Tab)
dTab

In [ ]:
Quadrance_A1*dTab**2/((np.linalg.norm(np.matmul(p,Tab)))**2 * (np.linalg.norm(np.matmul(q,Tab)))**2 *(np.linalg.norm(np.matmul(s,Tab)))**2)

In [ ]:
Quadrance_A2*dTab**2/((np.linalg.norm(np.matmul(p,Tab)))**2 * (np.linalg.norm(np.matmul(s,Tab)))**2 *(np.linalg.norm(np.matmul(r,Tab)))**2)

In [ ]:
Quadrance_A3*dTab**2/((np.linalg.norm(np.matmul(p,Tab)))**2 * (np.linalg.norm(np.matmul(q,Tab)))**2 *(np.linalg.norm(np.matmul(r,Tab)))**2)

In [ ]:
Quadrance_A4*dTab**2/((np.linalg.norm(np.matmul(q,Tab)))**2 * (np.linalg.norm(np.matmul(s,Tab)))**2 *(np.linalg.norm(np.matmul(r,Tab)))**2)

In [ ]:
Quadrance_C1 = np.linalg.det(W1)/(W1[0,0]*W1[1,1]*W1[2,2])
Quadrance_C1

In [ ]:
Quadrance_C2 = np.linalg.det(W2)/(W2[0,0]*W2[1,1]*W2[2,2])
Quadrance_C2

In [ ]:
Quadrance_C3 = np.linalg.det(W3)/(W3[0,0]*W3[1,1]*W3[2,2])
Quadrance_C3

In [ ]:
Quadrance_C4 = np.linalg.det(W4)/(W4[0,0]*W4[1,1]*W4[2,2])
Quadrance_C4

In [ ]:
dTbc = np.linalg.det(Tbc)
dTbc

In [ ]:
Quadrance_A1*dTab**2*dTbc**2/(((np.linalg.norm(np.matmul(p,Tab)))**2 * (np.linalg.norm(np.matmul(q,Tab)))**2 *(np.linalg.norm(np.matmul(s,Tab)))**2) * ((np.linalg.norm(np.matmul(b1,Tbc)))**2 * (np.linalg.norm(np.matmul(b2,Tbc)))**2 *(np.linalg.norm(np.matmul(b3,Tbc)))**2))

In [ ]:
Quadrance_A2*dTab**2*dTbc**2/(((np.linalg.norm(np.matmul(p,Tab)))**2 * (np.linalg.norm(np.matmul(s,Tab)))**2 *(np.linalg.norm(np.matmul(r,Tab)))**2) * ((np.linalg.norm(np.matmul(b1,Tbc)))**2 * (np.linalg.norm(np.matmul(b3,Tbc)))**2 *(np.linalg.norm(np.matmul(b4,Tbc)))**2))

In [ ]:
Quadrance_A3*dTab**2*dTbc**2/(((np.linalg.norm(np.matmul(p,Tab)))**2 * (np.linalg.norm(np.matmul(q,Tab)))**2 *(np.linalg.norm(np.matmul(r,Tab)))**2) * ((np.linalg.norm(np.matmul(b1,Tbc)))**2 * (np.linalg.norm(np.matmul(b2,Tbc)))**2 *(np.linalg.norm(np.matmul(b4,Tbc)))**2))

In [ ]:
Quadrance_A4*dTab**2*dTbc**2/(((np.linalg.norm(np.matmul(q,Tab)))**2 * (np.linalg.norm(np.matmul(s,Tab)))**2 *(np.linalg.norm(np.matmul(r,Tab)))**2) * ((np.linalg.norm(np.matmul(b2,Tbc)))**2 * (np.linalg.norm(np.matmul(b3,Tbc)))**2 *(np.linalg.norm(np.matmul(b4,Tbc)))**2))

In [ ]:
dTac = np.linalg.det(Tac)
dTac

In [ ]:
Quadrance_A1*dTac**2

In [ ]:
Quadrance_A1*dTac**2/((np.linalg.norm(np.matmul(p,Tac)))**2 * (np.linalg.norm(np.matmul(q,Tac)))**2 *(np.linalg.norm(np.matmul(s,Tac)))**2)

In [ ]:
Quadrance_A2*dTac**2/((np.linalg.norm(np.matmul(p,Tac)))**2 * (np.linalg.norm(np.matmul(s,Tac)))**2 *(np.linalg.norm(np.matmul(r,Tac)))**2)

In [ ]:
Quadrance_A3*dTac**2/((np.linalg.norm(np.matmul(p,Tac)))**2 * (np.linalg.norm(np.matmul(q,Tac)))**2 *(np.linalg.norm(np.matmul(r,Tac)))**2)

In [ ]:
Quadrance_A4*dTac**2/((np.linalg.norm(np.matmul(q,Tac)))**2 * (np.linalg.norm(np.matmul(s,Tac)))**2 *(np.linalg.norm(np.matmul(r,Tac)))**2)