# Quadrea of Projective Triangle From Exemplary Transformation

<img src="Spherical Geometry Triangle.png">


In [1]:
import numpy as np

In [2]:
A = np.random.rand(3,3)
A

array([[0.98790968, 0.59738496, 0.15443552],
       [0.89996412, 0.4243651 , 0.89873798],
       [0.5517799 , 0.98088507, 0.22513405]])

In [3]:
p = A[0,:]
q = A[1,:]
s = A[2,:]

In [4]:
p = p / np.linalg.norm(p)
q = q / np.linalg.norm(q)
s = s / np.linalg.norm(s)

In [5]:
B = np.random.rand(3,3)
B

array([[0.14180851, 0.73447195, 0.81933023],
       [0.69250573, 0.02756186, 0.34199189],
       [0.68007066, 0.0765425 , 0.662035  ]])

In [6]:
P = B[0,:]
Q = B[1,:]
S = B[2,:]

In [7]:
P = P / np.linalg.norm(P)
Q = Q / np.linalg.norm(Q)
S = S / np.linalg.norm(S)

In [8]:
sq = np.cross(s,q)
print(sq)

[ 0.51077454 -0.19058887 -0.42147935]


In [9]:
ps = np.cross(p,s)
print(ps)

[-0.01271044 -0.1026285   0.47829339]


In [10]:
qp = np.cross(q,p)
print(qp)

[-0.30181745  0.47952493  0.07580767]


In [11]:
sqP = np.outer(sq,P)
print(sqP)

[[ 0.06528706  0.33814269  0.37721049]
 [-0.02436102 -0.12617354 -0.14075118]
 [-0.05387337 -0.27902753 -0.31126538]]


In [12]:
psQ = np.outer(ps,Q)
print(psQ)

[[-0.01138922 -0.00045329 -0.00562453]
 [-0.09196054 -0.00366005 -0.04541444]
 [ 0.42857608  0.01705741  0.21165102]]


In [13]:
qpS = np.outer(qp,S)
print(qpS)

[[-0.21556572 -0.02426209 -0.20984886]
 [ 0.34248894  0.0385474   0.33340604]
 [ 0.05414377  0.00609392  0.05270786]]


In [14]:
np.matmul(q,psQ)

array([0.25052376, 0.00997089, 0.12372041])

In [15]:
Q

array([0.8960527 , 0.03566307, 0.44251295])

In [16]:
np.matmul(p,sqP)

array([0.0357366 , 0.18509135, 0.20647615])

In [17]:
P

array([0.12781971, 0.66201946, 0.73850684])

In [18]:
np.matmul(s,qpS)

array([0.19968743, 0.02247498, 0.19439166])

In [19]:
S

array([0.71422551, 0.08038665, 0.69528405])

In [20]:
alpha = P[0]/(np.matmul(p,sqP)[0])
beta = Q[0]/(np.matmul(q,psQ)[0])
gamma = S[0]/(np.matmul(s,qpS)[0])

# T is the transformation matrix

In [21]:
T = alpha*sqP + beta*psQ + gamma*qpS

In [22]:
np.matmul(p,T)

array([0.12781971, 0.66201946, 0.73850684])

In [23]:
P

array([0.12781971, 0.66201946, 0.73850684])

In [24]:
np.matmul(q,T)

array([0.8960527 , 0.03566307, 0.44251295])

In [25]:
Q

array([0.8960527 , 0.03566307, 0.44251295])

In [26]:
np.matmul(s,T)

array([0.71422551, 0.08038665, 0.69528405])

In [27]:
S

array([0.71422551, 0.08038665, 0.69528405])

In [28]:
dT = np.linalg.det(T)
print(T)
print(dT)

[[-0.57824036  1.12104089  0.5784879 ]
 [ 0.80893682 -0.32650489  0.52663736]
 [ 1.53386267 -0.91519685 -0.1677713 ]]
0.6087741119259577


In [29]:
dT*dT

0.37060591935123843

In [30]:
A = np.array([p,q,s])
print(A)

[[0.84815999 0.5128789  0.13258907]
 [0.67121308 0.31650085 0.6702986 ]
 [0.48075799 0.85463123 0.1961561 ]]


In [31]:
B = np.array([P,Q,S])
print(B)

[[0.12781971 0.66201946 0.73850684]
 [0.8960527  0.03566307 0.44251295]
 [0.71422551 0.08038665 0.69528405]]


In [32]:
At = A.transpose()
print(At)

[[0.84815999 0.67121308 0.48075799]
 [0.5128789  0.31650085 0.85463123]
 [0.13258907 0.6702986  0.1961561 ]]


In [33]:
Bt = B.transpose()
print(Bt)

[[0.12781971 0.8960527  0.71422551]
 [0.66201946 0.03566307 0.08038665]
 [0.73850684 0.44251295 0.69528405]]


In [34]:
U = np.matmul(A,At)
U

array([[1.        , 0.82049696, 0.87209017],
       [0.82049696, 1.        , 0.72466572],
       [0.87209017, 0.72466572, 1.        ]])

In [35]:
V = np.matmul(B,Bt)
V

array([[1.        , 0.46494169, 0.65798166],
       [0.46494169, 1.        , 0.95052272],
       [0.65798166, 0.95052272, 1.        ]])

In [36]:
Su = np.linalg.det(U)/(U[0,0]*U[1,1]*U[2,2])
Su

0.07816831336054614

# We get the result that quadrea Sv is equal to quadrea Su times determinant of T squared

In [37]:
Sv = np.linalg.det(V)/(V[0,0]*V[1,1]*V[2,2])
Sv

0.02896963963712123

In [38]:
Su*dT**2

0.028969639637120896